spring:
  datasource:
    url: jdbc:postgresql://payment-db.c7wu20i6mma7.us-east-2.rds.amazonaws.com:5432/postgres
    username: postgres
    password: teste123

queues:
  gerar_qr_code: gerar_qr_code
  qr_code_gerado: qr_code_gerado
  realiza_pagamento: realiza_pagamento
  pagamento_concluido: pagamento_concluido


server:
  port: 9090
  servlet:
    context-path: /fiap-payments

