spring:
  datasource:
    url: ${URL_BD:jdbc:postgresql://localhost:5432/postgres?currentSchema=sch_payments}
    username: postgres
    password: 123
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}

queue01:
  gerar_qr_code: gerar_qr_code
queue02:
  qr_code_gerado: qr_code_gerado
queue03:
  realiza_pagamento: realiza_pagamento
queue04:
  pagamento_concluido: pagamento_concluido


server:
  port: 9090
  servlet:
    context-path: /fiap-payments

