spring:
  datasource:
    url: ${URL_BD:jdbc:postgresql://localhost:5432/postgres?currentSchema=sch_payments}
    username: postgres
    password: teste123

queues:
  gerar_qr_code: gerar_qr_code
  qr_code_gerado: qr_code_gerado
  realiza_pagamento: realiza_pagamento
  pagamento_concluido: pagamento_concluido


server:
  port: 9090
  servlet:
    context-path: /fiap-payments

