spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}

queue:
  gerar_qr_code: gerar_qr_code
  qr_code_gerado: qr_code_gerado
  realiza_pagamento: realiza_pagamento



server:
  port: 9090
  servlet:
    context-path: /fiap-payments

